stages:
    - test
    - deploy

test 7.1:
    image: alpine:3.7
    stage: test
    parallel:
        matrix:
            - COMPOSER_PREFER: [lowest, latest]
    before_script:
        - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        - php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
        - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        - php -r "unlink('composer-setup.php');"
    script:
        - ./tests.sh "composer_update_prefer_$COMPOSER_PREFER"
        - ./tests.sh phpunit_with_coverage
        - ./tests.sh phpmd
    artifacts:
        paths:
            - phpmd.html
            - coverage
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.2:
    image: alpine:3.9
    stage: test
    parallel:
        matrix:
            - COMPOSER_PREFER: [lowest, latest]
    before_script:
        - apk add --no-cache composer
    script:
        - ./tests.sh "composer_update_prefer_$COMPOSER_PREFER"
        - ./tests.sh phpunit
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.3:
    image: alpine:3.12
    stage: test
    parallel:
        matrix:
            - COMPOSER_PREFER: [lowest, latest]
    before_script:
        - apk add --no-cache composer
    script:
        - ./tests.sh "composer_update_prefer_$COMPOSER_PREFER"
        - ./tests.sh phpunit
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.4:
    image: alpine:edge
    stage: test
    parallel:
        matrix:
            - COMPOSER_PREFER: [lowest, latest]
    before_script:
        - apk add --no-cache composer
    script:
        - ./tests.sh "composer_update_prefer_$COMPOSER_PREFER"
        - ./tests.sh phpunit
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 8.0:
    image: alpine:edge
    stage: test
    parallel:
        matrix:
            - COMPOSER_PREFER: [lowest, latest]
    before_script:
        - apk add --no-cache composer
    script:
        - ./tests.sh "composer_update_prefer_$COMPOSER_PREFER"
        - ./tests.sh phpunit
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

pages:
    image: docker:latest
    stage: deploy
    script:
        - mkdir public
        - mv coverage public/
        - mv phpmd.html public/
        - echo "Visit https://anezi.gitlab.io/locale-extension/phpmd.html to see phpmd report."
        - echo "Visit https://anezi.gitlab.io/locale-extension/coverage to see coverage results."
    artifacts:
        paths:
            - public
    only:
        - master
