stages:
    - test
    - deploy

test 7.1:
    image: alpine:3.7
    stage: test
    parallel:
        matrix:
            - COMPOSER: [lowest, latest]
    before_script:
        - apk add --no-cache composer
    script:
        - ./tests.sh "composer_update_prefer_$COMPOSER"
        - ./tests.sh phpunit_with_coverage
        - ./tests.sh phpmd
    artifacts:
        paths:
            - phpmd.html
            - coverage
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.2:
    image: alpine:3.9
    stage: test
    parallel:
        matrix:
            - COMPOSER: [lowest, latest]
    before_script:
        - apk add --no-cache composer
    script:
        - ./tests.sh "composer_update_prefer_$COMPOSER"
        - ./tests.sh phpunit
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.3:
    image: alpine:3.12
    stage: test
    parallel:
        matrix:
            - COMPOSER: [lowest, latest]
    before_script:
        - apk add --no-cache composer
    script:
        - ./tests.sh "composer_update_prefer_$COMPOSER"
        - ./tests.sh phpunit
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.4:
    image: alpine:edge
    stage: test
    parallel:
        matrix:
            - COMPOSER: [lowest, latest]
    before_script:
        - apk add --no-cache composer
    script:
        - ./tests.sh "composer_update_prefer_$COMPOSER"
        - ./tests.sh phpunit
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 8.0:
    image: alpine:edge
    stage: test
    parallel:
        matrix:
            - COMPOSER: [lowest, latest]
    before_script:
        - apk add --no-cache composer
    script:
        - ./tests.sh "composer_update_prefer_$COMPOSER"
        - ./tests.sh phpunit
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

pages:
    image: docker:latest
    stage: deploy
    script:
        - mkdir public
        - mv coverage public/
        - mv phpmd.html public/
        - echo "Visit https://anezi.gitlab.io/locale-extension/phpmd.html to see phpmd report."
        - echo "Visit https://anezi.gitlab.io/locale-extension/coverage to see coverage results."
    artifacts:
        paths:
            - public
    only:
        - master
