stages:
    - test
    - deploy

test 7.1 lowest:
    image: registry.gitlab.com/anezi/php-dev:7.1
    stage: test
    script:
        - ./tests composer_update_prefer_lowest
        - ./tests phpunit
        - ./tests phpmd
    artifacts:
        paths:
            - phpmd.html
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.1 latest:
    image: registry.gitlab.com/anezi/php-dev:7.1
    stage: test
    script:
        - ./tests composer_update_prefer_latest
        - ./tests phpunit_with_coverage
    artifacts:
        paths:
            - coverage
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.2 lowest:
    image: registry.gitlab.com/anezi/php-dev:7.2
    stage: test
    script:
        - ./tests composer_update_prefer_lowest
        - ./tests phpunit
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.2 latest:
    image: registry.gitlab.com/anezi/php-dev:7.2
    stage: test
    script:
        - ./tests composer_update_prefer_latest
        - ./tests phpunit
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

pages:
    image: docker:latest
    stage: deploy
    script:
        - mkdir public
        - mv coverage public/
        - mv phpmd.html public/
        - echo "Visit https://packages.pages.anezi.net/locale to verify the results."
    artifacts:
        paths:
            - public
    only:
        - master
